/* eslint-disable max-len */
const constant = {
  CUSTOMER: {
    LISTEN: {
      ON_CHANGED_ORDER_STATUS: 'ON_CHANGED_ORDER_STATUS', // use for 2 app {"type":"CONFIRMED_ORDER","message":"Your order has been comfirmed.","data":{"order_id":"K20581MIBKE"}}
      ON_NOTFOUND_ORDER: 'ON_NOTFOUND_ORDER',
      ON_CHANGE_SHOP_CONFIRM: 'ON_CHANGE_SHOP_CONFIRM',
      ON_ALL_REJECTED: 'ON_ALL_REJECTED',
      ON_KENO_NOTIFY: 'KENO_NOTIFY',
      ON_GET_PROMOTION: 'GET_PROMOTION',
      ON_TRACKING_STAFF_LOCATION: 'TRACKING_STAFF_LOCATION',
      ON_CHANGED_SUBSCRIPTION: 'ON_CHANGED_SUBSCRIPTION'
    },
    EMIT: {
      TIP: 'MAKE_TIP_FOR_STAFF',
      SUBSCRIPTION: 'NEW_SUBSCRIPTION',
      TOP_UP_SUBSCRIPTION: 'TOP_UP_SUBSCRIPTION',
    }
  },
  STAFF: { // APP
    LISTEN: {
      ON_CHANGED_ORDER_STATUS: 'ON_CHANGED_ORDER_STATUS',
      ON_KENO_NOTIFY: 'KENO_NOTIFY_TO_STAFF'
    },
    EMIT: {
      TRACKING_STAFF_LOCATION: 'TRACKING_STAFF_LOCATION'
    }
  },
  SHOP: {
    LISTEN: {
      ON_CHANGED_SHOPPING_ORDER_STATUS: 'ON_CHANGED_SHOPPING_ORDER_STATUS',
      ON_REJECTED: 'ON_REJECTED_ORDER',
      ON_NEW_ORDER: 'NEW_ORDER',
      ON_KENO_NOTIFY: 'KENO_NOTIFY_TO_SHOP'
    },
    EMIT: {

    }
  },
  ADMIN: {
    LISTEN: {
      ON_NEW_PROMOTION: 'NEW_PROMOTION',
      ON_NEW_COMPANY: 'NEW_COMPANY'
    }
  },
  GENERAL: {
    LISTEN: {
      GENERAL_NOTIFY: 'NOTIFICATION',
      REFRESH: 'REFRESH_DATA'
    }
  }
}
module.exports = constant
